name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: macos-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
